apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cas-knowledge-postgres
  namespace: cywell-ai-sentinel
spec:
  template:
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cas-knowledge-postgres-live
                  key: database
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cas-knowledge-postgres-live
                  key: username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cas-knowledge-postgres-live
                  key: password
                  optional: false
